<?php

require dirname(__DIR__) . '/app/bootstrap.php';

$schemas = require BASE_PATH . '/app/module_schemas.php';
$route = $_GET['route'] ?? (is_logged_in() ? 'home' : 'login');
enforce_route_permission($route);

match ($route) {
    'login' => $_SERVER['REQUEST_METHOD'] === 'POST'
        ? (new AuthController())->login($config, $store)
        : (new AuthController())->showLogin($config),
    'logout' => (new AuthController())->logout(),
    'profile' => $_SERVER['REQUEST_METHOD'] === 'POST'
        ? (new AuthController())->updateProfile($store)
        : (new AuthController())->profile(),
    'password' => $_SERVER['REQUEST_METHOD'] === 'POST'
        ? (new AuthController())->updatePassword($config, $store)
        : (new AuthController())->password(),
    'home' => (new DashboardController())->home($store),
    'dashboard' => (new DashboardController())->index($store),
    'employees' => (new EmployeeController())->index($store),
    'employees.show' => (new EmployeeController())->show($store),
    'employees.export' => (new EmployeeController())->export($store),
    'employees.template' => (new EmployeeController())->template(),
    'employees.import' => (new EmployeeController())->import($store),
    'contracts' => (new ContractController())->index($store),
    'contracts.save' => (new ContractController())->save($store),
    'contracts.delete' => (new ContractController())->delete($store),
    'contracts.export' => (new ContractController())->export($store),
    'attendance' => (new AttendanceController())->index($store),
    'attendance.process' => (new AttendanceController())->process($store),
    'attendance.process.generate' => (new AttendanceController())->generate($store),
    'attendance.process.violation' => (new AttendanceController())->markViolations($store),
    'attendance.manage' => (new AttendanceController())->manage($store),
    'attendance.manage.save' => (new AttendanceController())->saveMachine($store),
    'attendance.manage.delete' => (new AttendanceController())->deleteMachine($store),
    'payrolls' => (new PayrollController())->index($store),
    'payrolls.save' => (new PayrollController())->save($store),
    'payrolls.complete' => (new PayrollController())->complete($store),
    'payrolls.delete' => (new PayrollController())->delete($store),
    'payrolls.export' => (new PayrollController())->export($store),
    'social-insurance' => (new SocialInsuranceController())->index($store),
    'social-insurance.save' => (new SocialInsuranceController())->save($store),
    'social-insurance.delete' => (new SocialInsuranceController())->delete($store),
    'requests' => (new RequestFormController())->index($store),
    'requests.save' => (new RequestFormController())->save($store),
    'requests.approval' => (new RequestFormController())->approval($store),
    'requests.delete' => (new RequestFormController())->delete($store),
    'violations' => (new ViolationController())->index($store),
    'violations.save' => (new ViolationController())->save($store),
    'violations.delete' => (new ViolationController())->delete($store),
    'rewards' => (new RewardController())->index($store),
    'rewards.save' => (new RewardController())->save($store),
    'rewards.delete' => (new RewardController())->delete($store),
    'projects' => (new ProjectController())->index($store),
    'projects.save' => (new ProjectController())->save($store),
    'projects.delete' => (new ProjectController())->delete($store),
    'projects.template' => (new ProjectController())->template(),
    'projects.import' => (new ProjectController())->import($store),
    'work-items' => (new WorkItemController())->index($store),
    'work-items.save' => (new WorkItemController())->save($store),
    'work-items.delete' => (new WorkItemController())->delete($store),
    'daily-reports' => (new DailyReportController())->index($store),
    'daily-reports.save' => (new DailyReportController())->saveBatch($store),
    'daily-reports.update' => (new DailyReportController())->update($store),
    'daily-reports.delete' => (new DailyReportController())->delete($store),
    'suppliers' => (new SupplierController())->index($store),
    'suppliers.save' => (new SupplierController())->save($store),
    'suppliers.delete' => (new SupplierController())->delete($store),
    'suppliers.import' => (new SupplierController())->import($store),
    'services' => (new ServiceController())->index($store),
    'services.create' => (new ServiceController())->create($store),
    'services.edit' => (new ServiceController())->edit($store),
    'services.show' => (new ServiceController())->show($store),
    'services.save' => (new ServiceController())->save($store),
    'services.toggle' => (new ServiceController())->toggle($store),
    'services.delete' => (new ServiceController())->delete($store),
    'products' => (new ProductController())->index($store),
    'products.save' => (new ProductController())->save($store),
    'products.delete' => (new ProductController())->delete($store),
    'sales-orders' => (new SalesOrderController())->index($store),
    'sales-orders.save' => (new SalesOrderController())->save($store),
    'sales-orders.delete' => (new SalesOrderController())->delete($store),
    'sales-targets' => (new SalesTargetController())->index($store),
    'sales-targets.save' => (new SalesTargetController())->save($store),
    'sales-targets.delete' => (new SalesTargetController())->delete($store),
    'sales-receipts' => (new SalesReceiptController())->index($store),
    'sales-receipts.save' => (new SalesReceiptController())->save($store),
    'sales-receipts.delete' => (new SalesReceiptController())->delete($store),
    'machine-warehouses' => (new MachineWarehouseController())->index($store),
    'machine-warehouses.save' => (new MachineWarehouseController())->save($store),
    'machine-warehouses.transfer' => (new MachineWarehouseController())->transfer($store),
    'machine-warehouses.delete' => (new MachineWarehouseController())->delete($store),
    'equipment-devices' => (new EquipmentDeviceController())->index($store),
    'equipment-devices.save' => (new EquipmentDeviceController())->save($store),
    'equipment-devices.import' => (new EquipmentDeviceController())->import($store),
    'equipment-devices.delete' => (new EquipmentDeviceController())->delete($store),
    'equipment-types' => (new EquipmentTypeController())->index($store),
    'equipment-types.save' => (new EquipmentTypeController())->save($store),
    'equipment-types.delete' => (new EquipmentTypeController())->delete($store),
    'purchasing' => (new PurchasingController())->index($store),
    'purchasing.save' => (new PurchasingController())->save($store),
    'purchasing.approval' => (new PurchasingController())->approval($store),
    'purchasing.delete' => (new PurchasingController())->delete($store),
    'recruitment-requests' => (new RecruitmentRequestController())->index($store),
    'recruitment-requests.save' => (new RecruitmentRequestController())->save($store),
    'recruitment-requests.approval' => (new RecruitmentRequestController())->approval($store),
    'recruitment-requests.delete' => (new RecruitmentRequestController())->delete($store),
    'resource' => redirect('home'),
    'resource.save' => (new ResourceController())->save($store, $schemas),
    'resource.delete' => (new ResourceController())->delete($store, $schemas),
    'reset' => $_SERVER['REQUEST_METHOD'] === 'POST'
        ? (new ResourceController())->reset($store)
        : redirect('home'),
    'tasks' => (new TaskController())->index($store),
    'reports' => (new ReportController())->index($store),
    'reports.export' => (new ReportController())->export($store),
    'permissions' => (new PermissionController())->index($store),
    'permissions.save' => (new PermissionController())->save($store),
    'calls' => (new CallController())->index($store),
    'calls.save' => (new CallController())->save($store),
    'search' => (new SearchController())->index($store, $schemas),
    'notification.read' => (new NotificationController())->read($store),
    'notification.readAll' => (new NotificationController())->readAll($store),
    default => redirect('home'),
};
