<?php

return [
    'users' => [
        'title' => 'Người dùng và phân quyền',
        'subtitle' => 'Tài khoản, vai trò và trạng thái truy cập',
        'fields' => [
            ['name' => 'name', 'label' => 'Họ tên', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'role', 'label' => 'Vai trò', 'type' => 'select', 'options' => ['Admin', 'Manager', 'Sales', 'HR', 'Warehouse']],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['active', 'locked']],
        ],
        'columns' => [
            ['name' => 'name', 'label' => 'Họ tên'],
            ['name' => 'email', 'label' => 'Email'],
            ['name' => 'role', 'label' => 'Vai trò'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'employees' => [
        'title' => 'Nhân sự',
        'subtitle' => 'Phòng ban, chức vụ, hợp đồng và trạng thái nhân viên',
        'fields' => [
            ['name' => 'attendance_code', 'label' => 'Mã chấm công', 'type' => 'text'],
            ['name' => 'employee_code', 'label' => 'Mã nhân viên', 'type' => 'text'],
            ['name' => 'name', 'label' => 'Nhân viên', 'type' => 'text'],
            ['name' => 'gender', 'label' => 'Giới tính', 'type' => 'select', 'options' => ['Nam', 'Nữ', 'Khác']],
            ['name' => 'email', 'label' => 'Địa chỉ email', 'type' => 'email'],
            ['name' => 'department', 'label' => 'Phòng ban', 'type' => 'select', 'options' => ['Kinh doanh', 'Nhân sự', 'Kho vận', 'Công nghệ', 'Tài chính']],
            ['name' => 'position', 'label' => 'Chức vụ', 'type' => 'text'],
            ['name' => 'contract', 'label' => 'Hợp đồng', 'type' => 'select', 'options' => ['Thử việc', 'Chính thức', 'Thời vụ']],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['active', 'on_leave', 'inactive']],
        ],
        'columns' => [
            ['name' => 'name', 'label' => 'Nhân viên'],
            ['name' => 'department', 'label' => 'Phòng ban'],
            ['name' => 'position', 'label' => 'Chức vụ'],
            ['name' => 'contract', 'label' => 'Hợp đồng'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'tasks' => [
        'title' => 'Công việc và dự án',
        'subtitle' => 'Giao việc, phân công, deadline và trạng thái hoàn thành',
        'fields' => [
            ['name' => 'title', 'label' => 'Tên công việc', 'type' => 'text'],
            ['name' => 'project', 'label' => 'Dự án / nhóm', 'type' => 'text'],
            ['name' => 'assignee', 'label' => 'Phụ trách', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['pending', 'in_progress', 'completed', 'canceled']],
            ['name' => 'deadline', 'label' => 'Deadline', 'type' => 'date'],
        ],
        'columns' => [
            ['name' => 'title', 'label' => 'Công việc'],
            ['name' => 'project', 'label' => 'Dự án'],
            ['name' => 'assignee', 'label' => 'Phụ trách'],
            ['name' => 'deadline', 'label' => 'Deadline'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'training' => [
        'title' => 'Đào tạo',
        'subtitle' => 'Lộ trình đào tạo, tài liệu học tập và kết quả huấn luyện',
        'fields' => [
            ['name' => 'course', 'label' => 'Khóa đào tạo', 'type' => 'text'],
            ['name' => 'employee', 'label' => 'Nhân viên', 'type' => 'text'],
            ['name' => 'trainer', 'label' => 'Người đào tạo', 'type' => 'text'],
            ['name' => 'progress', 'label' => 'Tiến độ (%)', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['pending', 'in_progress', 'completed']],
        ],
        'columns' => [
            ['name' => 'course', 'label' => 'Khóa đào tạo'],
            ['name' => 'employee', 'label' => 'Nhân viên'],
            ['name' => 'trainer', 'label' => 'Đào tạo bởi'],
            ['name' => 'progress', 'label' => 'Tiến độ'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'recruitments' => [
        'title' => 'Tuyển dụng',
        'subtitle' => 'Vị trí tuyển dụng, ứng viên và vòng xử lý',
        'fields' => [
            ['name' => 'position', 'label' => 'Vị trí', 'type' => 'text'],
            ['name' => 'candidate', 'label' => 'Ứng viên', 'type' => 'text'],
            ['name' => 'stage', 'label' => 'Vòng', 'type' => 'select', 'options' => ['screening', 'interview', 'offer', 'hired', 'rejected']],
            ['name' => 'owner', 'label' => 'Phụ trách', 'type' => 'text'],
        ],
        'columns' => [
            ['name' => 'position', 'label' => 'Vị trí'],
            ['name' => 'candidate', 'label' => 'Ứng viên'],
            ['name' => 'stage', 'label' => 'Vòng', 'format' => 'badge'],
            ['name' => 'owner', 'label' => 'Phụ trách'],
        ],
    ],
    'customers' => [
        'title' => 'Khách hàng và nhà cung cấp',
        'subtitle' => 'Khách hàng, đối tác, ticket chăm sóc và phân loại',
        'fields' => [
            ['name' => 'name', 'label' => 'Tên', 'type' => 'text'],
            ['name' => 'type', 'label' => 'Loại', 'type' => 'select', 'options' => ['customer', 'supplier']],
            ['name' => 'phone', 'label' => 'Điện thoại', 'type' => 'text'],
            ['name' => 'owner', 'label' => 'Phụ trách', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['new', 'active', 'vip', 'inactive']],
        ],
        'columns' => [
            ['name' => 'name', 'label' => 'Tên'],
            ['name' => 'type', 'label' => 'Loại', 'format' => 'badge'],
            ['name' => 'phone', 'label' => 'Điện thoại'],
            ['name' => 'owner', 'label' => 'Phụ trách'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'sales' => [
        'title' => 'Bán hàng',
        'subtitle' => 'Sản phẩm, dịch vụ, đơn hàng và thanh toán',
        'fields' => [
            ['name' => 'code', 'label' => 'Mã đơn', 'type' => 'text'],
            ['name' => 'customer', 'label' => 'Khách hàng', 'type' => 'text'],
            ['name' => 'product', 'label' => 'Sản phẩm / dịch vụ', 'type' => 'text'],
            ['name' => 'amount', 'label' => 'Giá trị', 'type' => 'number'],
            ['name' => 'payment', 'label' => 'Thanh toán', 'type' => 'select', 'options' => ['unpaid', 'partial', 'paid']],
            ['name' => 'status', 'label' => 'Trạng thái đơn', 'type' => 'select', 'options' => ['draft', 'confirmed', 'delivered', 'canceled']],
        ],
        'columns' => [
            ['name' => 'code', 'label' => 'Mã đơn'],
            ['name' => 'customer', 'label' => 'Khách hàng'],
            ['name' => 'product', 'label' => 'Sản phẩm'],
            ['name' => 'amount', 'label' => 'Giá trị', 'format' => 'money'],
            ['name' => 'payment', 'label' => 'Thanh toán', 'format' => 'badge'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'inventory' => [
        'title' => 'Kho',
        'subtitle' => 'SKU, tồn kho, nhập xuất và cảnh báo tồn thấp',
        'fields' => [
            ['name' => 'sku', 'label' => 'SKU', 'type' => 'text'],
            ['name' => 'name', 'label' => 'Sản phẩm', 'type' => 'text'],
            ['name' => 'warehouse', 'label' => 'Kho', 'type' => 'select', 'options' => ['Kho Hà Nội', 'Kho TP.HCM', 'Kho Đà Nẵng']],
            ['name' => 'quantity', 'label' => 'Tồn kho', 'type' => 'number'],
            ['name' => 'min', 'label' => 'Tồn tối thiểu', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['available', 'low', 'out']],
        ],
        'columns' => [
            ['name' => 'sku', 'label' => 'SKU'],
            ['name' => 'name', 'label' => 'Sản phẩm'],
            ['name' => 'warehouse', 'label' => 'Kho'],
            ['name' => 'quantity', 'label' => 'Tồn kho'],
            ['name' => 'min', 'label' => 'Tối thiểu'],
            ['name' => 'status', 'label' => 'Cảnh báo', 'format' => 'badge'],
        ],
    ],
    'kpi' => [
        'title' => 'KPI / OKR',
        'subtitle' => 'Mục tiêu, kết quả then chốt và tiến độ',
        'fields' => [
            ['name' => 'objective', 'label' => 'Mục tiêu', 'type' => 'text'],
            ['name' => 'owner', 'label' => 'Phụ trách', 'type' => 'text'],
            ['name' => 'metric', 'label' => 'Chỉ số', 'type' => 'text'],
            ['name' => 'progress', 'label' => 'Tiến độ (%)', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['on_track', 'risk', 'done']],
        ],
        'columns' => [
            ['name' => 'objective', 'label' => 'Mục tiêu'],
            ['name' => 'owner', 'label' => 'Phụ trách'],
            ['name' => 'metric', 'label' => 'Chỉ số'],
            ['name' => 'progress', 'label' => 'Tiến độ'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'okrs' => [
        'title' => 'OKR',
        'subtitle' => 'Mục tiêu chiến lược và kết quả then chốt theo cấp công ty/phòng ban/nhân viên',
        'fields' => [
            ['name' => 'objective', 'label' => 'Objective', 'type' => 'text'],
            ['name' => 'key_result', 'label' => 'Key result', 'type' => 'text'],
            ['name' => 'level', 'label' => 'Cấp', 'type' => 'select', 'options' => ['company', 'department', 'employee']],
            ['name' => 'owner', 'label' => 'Phụ trách', 'type' => 'text'],
            ['name' => 'progress', 'label' => 'Tiến độ (%)', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['on_track', 'risk', 'done']],
        ],
        'columns' => [
            ['name' => 'objective', 'label' => 'Objective'],
            ['name' => 'key_result', 'label' => 'Key result'],
            ['name' => 'level', 'label' => 'Cấp'],
            ['name' => 'owner', 'label' => 'Phụ trách'],
            ['name' => 'progress', 'label' => 'Tiến độ'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'suppliers' => [
        'title' => 'Nhà cung cấp',
        'subtitle' => 'Đối tác cung ứng, danh mục hàng hóa/dịch vụ và công nợ',
        'fields' => [
            ['name' => 'name', 'label' => 'Nhà cung cấp', 'type' => 'text'],
            ['name' => 'category', 'label' => 'Danh mục cung cấp', 'type' => 'text'],
            ['name' => 'phone', 'label' => 'Điện thoại', 'type' => 'text'],
            ['name' => 'debt', 'label' => 'Công nợ', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['active', 'inactive']],
        ],
        'columns' => [
            ['name' => 'name', 'label' => 'Nhà cung cấp'],
            ['name' => 'category', 'label' => 'Danh mục'],
            ['name' => 'phone', 'label' => 'Điện thoại'],
            ['name' => 'debt', 'label' => 'Công nợ', 'format' => 'money'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'services' => [
        'title' => 'Dịch vụ',
        'subtitle' => 'Danh mục dịch vụ, bảng giá và gói giải pháp',
        'fields' => [
            ['name' => 'name', 'label' => 'Dịch vụ', 'type' => 'text'],
            ['name' => 'package', 'label' => 'Gói giải pháp', 'type' => 'text'],
            ['name' => 'price', 'label' => 'Giá', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['active', 'inactive']],
        ],
        'columns' => [
            ['name' => 'name', 'label' => 'Dịch vụ'],
            ['name' => 'package', 'label' => 'Gói'],
            ['name' => 'price', 'label' => 'Giá', 'format' => 'money'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'pos' => [
        'title' => 'POS bán lẻ',
        'subtitle' => 'Bán hàng nhanh, hóa đơn bán lẻ và phương thức thanh toán',
        'fields' => [
            ['name' => 'invoice', 'label' => 'Mã hóa đơn', 'type' => 'text'],
            ['name' => 'cashier', 'label' => 'Thu ngân', 'type' => 'text'],
            ['name' => 'items', 'label' => 'Mặt hàng', 'type' => 'text'],
            ['name' => 'amount', 'label' => 'Tổng tiền', 'type' => 'number'],
            ['name' => 'payment_method', 'label' => 'Phương thức', 'type' => 'select', 'options' => ['cash', 'bank', 'card', 'ewallet']],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['paid', 'canceled']],
        ],
        'columns' => [
            ['name' => 'invoice', 'label' => 'Hóa đơn'],
            ['name' => 'cashier', 'label' => 'Thu ngân'],
            ['name' => 'items', 'label' => 'Mặt hàng'],
            ['name' => 'amount', 'label' => 'Tổng tiền', 'format' => 'money'],
            ['name' => 'payment_method', 'label' => 'Thanh toán'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'tickets' => [
        'title' => 'Chăm sóc khách hàng',
        'subtitle' => 'Ticket hỗ trợ, lịch sử tương tác và phân loại khách hàng',
        'fields' => [
            ['name' => 'code', 'label' => 'Mã ticket', 'type' => 'text'],
            ['name' => 'customer', 'label' => 'Khách hàng', 'type' => 'text'],
            ['name' => 'issue', 'label' => 'Nội dung hỗ trợ', 'type' => 'text'],
            ['name' => 'owner', 'label' => 'Phụ trách', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['new', 'in_progress', 'completed', 'canceled']],
        ],
        'columns' => [
            ['name' => 'code', 'label' => 'Ticket'],
            ['name' => 'customer', 'label' => 'Khách hàng'],
            ['name' => 'issue', 'label' => 'Nội dung'],
            ['name' => 'owner', 'label' => 'Phụ trách'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'internal_assets' => [
        'title' => 'Kho nội bộ',
        'subtitle' => 'Vật tư, công cụ nội bộ, cấp phát và sử dụng tài sản',
        'fields' => [
            ['name' => 'code', 'label' => 'Mã tài sản', 'type' => 'text'],
            ['name' => 'name', 'label' => 'Tên tài sản', 'type' => 'text'],
            ['name' => 'assigned_to', 'label' => 'Cấp phát cho', 'type' => 'text'],
            ['name' => 'quantity', 'label' => 'Số lượng', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['available', 'in_use', 'maintenance']],
        ],
        'columns' => [
            ['name' => 'code', 'label' => 'Mã'],
            ['name' => 'name', 'label' => 'Tài sản'],
            ['name' => 'assigned_to', 'label' => 'Cấp phát'],
            ['name' => 'quantity', 'label' => 'Số lượng'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'calendar' => [
        'title' => 'Lịch làm việc',
        'subtitle' => 'Lịch họp, lịch công tác, sự kiện nội bộ và nhắc việc',
        'fields' => [
            ['name' => 'title', 'label' => 'Sự kiện', 'type' => 'text'],
            ['name' => 'type', 'label' => 'Loại lịch', 'type' => 'select', 'options' => ['meeting', 'business_trip', 'internal_event', 'reminder']],
            ['name' => 'owner', 'label' => 'Phụ trách', 'type' => 'text'],
            ['name' => 'date', 'label' => 'Ngày', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['pending', 'completed', 'canceled']],
        ],
        'columns' => [
            ['name' => 'title', 'label' => 'Sự kiện'],
            ['name' => 'type', 'label' => 'Loại'],
            ['name' => 'owner', 'label' => 'Phụ trách'],
            ['name' => 'date', 'label' => 'Ngày'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'facilities' => [
        'title' => 'Cơ sở vật chất',
        'subtitle' => 'Tài sản cố định, phòng họp, phương tiện và thiết bị công ty',
        'fields' => [
            ['name' => 'code', 'label' => 'Mã', 'type' => 'text'],
            ['name' => 'name', 'label' => 'Tên', 'type' => 'text'],
            ['name' => 'type', 'label' => 'Loại', 'type' => 'select', 'options' => ['fixed_asset', 'meeting_room', 'vehicle', 'equipment']],
            ['name' => 'location', 'label' => 'Vị trí', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['available', 'in_use', 'maintenance']],
        ],
        'columns' => [
            ['name' => 'code', 'label' => 'Mã'],
            ['name' => 'name', 'label' => 'Tên'],
            ['name' => 'type', 'label' => 'Loại'],
            ['name' => 'location', 'label' => 'Vị trí'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'permissions' => [
        'title' => 'Phân quyền',
        'subtitle' => 'Vai trò người dùng và quyền truy cập theo chức năng',
        'fields' => [
            ['name' => 'role', 'label' => 'Vai trò', 'type' => 'text'],
            ['name' => 'module', 'label' => 'Phân hệ', 'type' => 'text'],
            ['name' => 'can_view', 'label' => 'Xem', 'type' => 'select', 'options' => ['yes', 'no']],
            ['name' => 'can_create', 'label' => 'Thêm', 'type' => 'select', 'options' => ['yes', 'no']],
            ['name' => 'can_update', 'label' => 'Sửa', 'type' => 'select', 'options' => ['yes', 'no']],
            ['name' => 'can_delete', 'label' => 'Xóa', 'type' => 'select', 'options' => ['yes', 'no']],
        ],
        'columns' => [
            ['name' => 'role', 'label' => 'Vai trò'],
            ['name' => 'module', 'label' => 'Phân hệ'],
            ['name' => 'can_view', 'label' => 'Xem'],
            ['name' => 'can_create', 'label' => 'Thêm'],
            ['name' => 'can_update', 'label' => 'Sửa'],
            ['name' => 'can_delete', 'label' => 'Xóa'],
        ],
    ],
    'settings' => [
        'title' => 'Thông tin hệ thống',
        'subtitle' => 'Thông tin doanh nghiệp, tham số và chính sách hệ thống',
        'fields' => [
            ['name' => 'key', 'label' => 'Tham số', 'type' => 'text'],
            ['name' => 'value', 'label' => 'Giá trị', 'type' => 'text'],
            ['name' => 'group', 'label' => 'Nhóm', 'type' => 'select', 'options' => ['company', 'policy', 'system']],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['active', 'inactive']],
        ],
        'columns' => [
            ['name' => 'key', 'label' => 'Tham số'],
            ['name' => 'value', 'label' => 'Giá trị'],
            ['name' => 'group', 'label' => 'Nhóm'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
        ],
    ],
    'shipments' => [
        'title' => 'Vận chuyển',
        'subtitle' => 'Đơn giao hàng, đơn vị vận chuyển và tiến trình',
        'fields' => [
            ['name' => 'code', 'label' => 'Mã vận đơn', 'type' => 'text'],
            ['name' => 'order', 'label' => 'Đơn hàng', 'type' => 'text'],
            ['name' => 'carrier', 'label' => 'Đơn vị vận chuyển', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Trạng thái', 'type' => 'select', 'options' => ['packing', 'shipping', 'delivered', 'delayed']],
            ['name' => 'eta', 'label' => 'Ngày dự kiến', 'type' => 'date'],
        ],
        'columns' => [
            ['name' => 'code', 'label' => 'Mã vận đơn'],
            ['name' => 'order', 'label' => 'Đơn hàng'],
            ['name' => 'carrier', 'label' => 'Đơn vị'],
            ['name' => 'status', 'label' => 'Trạng thái', 'format' => 'badge'],
            ['name' => 'eta', 'label' => 'ETA'],
        ],
    ],
];
