CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(60) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE departments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE employees (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  department VARCHAR(120) NOT NULL,
  position VARCHAR(120) NOT NULL,
  contract VARCHAR(60) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE tasks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  project VARCHAR(120) NOT NULL,
  assignee VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL,
  deadline DATE NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE training (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  course VARCHAR(160) NOT NULL,
  employee VARCHAR(120) NOT NULL,
  trainer VARCHAR(120) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE recruitments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  position VARCHAR(120) NOT NULL,
  candidate VARCHAR(120) NOT NULL,
  stage VARCHAR(30) NOT NULL,
  owner VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  type VARCHAR(30) NOT NULL,
  phone VARCHAR(40) NULL,
  owner VARCHAR(120) NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE suppliers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  category VARCHAR(160) NOT NULL,
  phone VARCHAR(40) NULL,
  debt DECIMAL(15,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE services (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  package VARCHAR(160) NOT NULL,
  price DECIMAL(15,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE sales (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  customer VARCHAR(160) NOT NULL,
  product VARCHAR(160) NOT NULL,
  amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  payment VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE pos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  invoice VARCHAR(60) NOT NULL UNIQUE,
  cashier VARCHAR(120) NOT NULL,
  items VARCHAR(255) NOT NULL,
  amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE tickets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(60) NOT NULL UNIQUE,
  customer VARCHAR(160) NOT NULL,
  issue VARCHAR(255) NOT NULL,
  owner VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE inventory (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  warehouse VARCHAR(120) NOT NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  min DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE internal_assets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  assigned_to VARCHAR(160) NOT NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE kpi (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  objective VARCHAR(180) NOT NULL,
  owner VARCHAR(120) NOT NULL,
  metric VARCHAR(120) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE okrs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  objective VARCHAR(180) NOT NULL,
  key_result VARCHAR(220) NOT NULL,
  level VARCHAR(30) NOT NULL,
  owner VARCHAR(120) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE shipments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(60) NOT NULL UNIQUE,
  `order` VARCHAR(60) NOT NULL,
  carrier VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL,
  eta DATE NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE calendar (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  type VARCHAR(40) NOT NULL,
  owner VARCHAR(120) NOT NULL,
  date DATE NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE facilities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  type VARCHAR(40) NOT NULL,
  location VARCHAR(160) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE permissions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(80) NOT NULL,
  module VARCHAR(120) NOT NULL,
  can_view VARCHAR(10) NOT NULL DEFAULT 'no',
  can_create VARCHAR(10) NOT NULL DEFAULT 'no',
  can_update VARCHAR(10) NOT NULL DEFAULT 'no',
  can_delete VARCHAR(10) NOT NULL DEFAULT 'no',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE TABLE settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(120) NOT NULL UNIQUE,
  value VARCHAR(255) NOT NULL,
  `group` VARCHAR(60) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);
